### ISSUE TITLE
[Feature request] Implement InstanceGroups

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#105]
This needs to be implemented:
https://cloud.google.com/compute/docs/instance-groups/

Creating an issue to track and discuss logic, continuing the conversation from #81

**Comment by mlazarov** [comment]
Hi Temikus!

> Also, looking into instance groups a bit more deeply, I realised that it is a bit more complicated, since as far as I understand from the doc it isn't possible to just add an instance to the group later. The group needs to be created first with a specified template or a new instance spawned in the group and Vagrant attaching to it, which will require some heavy branching logic. I created an issue to discuss this further: #105

They are few types of Instance Groups. I think that it's easier to use (without complications of using templates) Unmanaged Instance Groups:
https://cloud.google.com/compute/docs/instance-groups/unmanaged-groups 
They can just be created and used (without templates or something else). 

To implement instance group management for fog-google I'm using Unmanaged Instance Groups  https://github.com/fog/fog-google/pull/62

I hope this helps.

**Comment by Temikus** [comment]
@mlazarov Ah, got it! Was thinking of managed.

So, since instance_groups are implemented, I can start working on this as soon as I have some cycles.

So:
- Implementing config parameter `instance_groups`, type: `Array`.
- Implement the logic in AssignInstanceGroups action (assuming looping through instance groups):
  - Check the Instance Groups existence - if none found - create the group. If the group cannot be created - hard fail, roll back and Error message that the group could not be created.
  - Assign instance to the instance group - if failed - hard fail, roll back and Error message that the group could not be assigned.

Sounds good for your use-case?

**Comment by mlazarov** [comment]
I'm not sure why the type of `instance_groups` have to be `Array` - may be I'm not following correctly your idea but one VM instance can be member to only one Instance Group.

**Comment by Temikus** [comment]
@mlazarov Ah, my mistake, changed to `String`.
Looks ok otherwise?

**Comment by mlazarov** [comment]
Yep, looks perfect for me :)

**Comment by ericmand** [comment]
I'd be interested in using instance_group. Any status?

**Comment by Temikus** [comment]
@ericmand - I'm a bit strapped for time but it's on my TODO list. I'll try to take a look this long weekend.
Pull requests are always welcome though :)
