### ISSUE TITLE
Rename rsync__excludes to rsync__exclude

### ISSUE THREAD

**Issue by p0deje** [mitchellh/vagrant-google#109]
I know that custom sync folders implementation has been returned only temporarily, but it was a bit confusing to me that there is a slight difference in RSync usage.

With pure Vagrant, we can exclude certain directories from being synced by setting `rsync__exclude` option:

``` ruby
Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__exclude: %w[.git/]
end
```

With vagrant-google, the same can be done using `rsync_excludes` (note trailing "s"):

``` ruby
Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__excludes: %w[.git/]
end
```

I'm not sure what exactly should be done here since custom implementation is to be removed and maybe `rsync_excludes` is already used by a lot of people so we cannot just rename it, but for the sake of someone looking for this (or just going over issues list), I think it makes sense to post this.

**Comment by Temikus** [comment]
@p0deje This should be fixed, new release that uses built-in rsync is now available.

**Comment by p0deje** [comment]
Thank you!
