### ISSUE TITLE
override.ssh.username does not respect YAML variable

### ISSUE THREAD

**Issue by soudaburger** [mitchellh/vagrant-google#111]
When attempting to run vagrant up against google compute, I ran into an issue where SSH connection hangs.  In order for my team to share code, we kep our Vagrantfile configuration variables in a local YAML file that does not get checked into version control.  When sourcing values for the ssh username, the YAML values do not appear to be loading or inheriting correctly.

```settings = YAML.load_file 'vagrant.yml'```
Does not work: ```override.ssh.username = settings['google']['google_ssh_username']```
Works ```override.ssh.username = ENV['GOOGLE_SSH_USER']```

All other YAML-loaded values are imported correctly.

**Comment by soudaburger** [comment]
### Relevant Vagrantfile

\# -*- mode: ruby -*-
\# vi: set ft=ruby :
require 'yaml'
settings                 = YAML.load_file 'vagrant.yml'
google_client_email      = settings['google']['google_client_email']
google_project_id        = settings['google']['google_project_id']
google_json_key_location = settings['google']['google_json_key_location']
google_image             = settings['google']['google_image']
google_zone              = settings['google']['google_zone']
google_ssh_username      = settings['google']['google_zone']
google_name              = settings['google']['google_name']
google_local_ssh_key     = settings['google']['google_local_ssh_key']

Vagrant.configure("2") do |config|
  config.vm.provider :google do |google, override|
    google.name                     = google_name
    google.google_project_id        = google_project_id
    google.google_client_email      = google_client_email
    google.google_json_key_location = google_json_key_location
    google.preemptible              = false
    google.on_host_maintenance      = 'TERMINATE'
    google.auto_restart             = true
    google.image                    = google_image
    google.zone                     = google_zone
    override.ssh.username           = google_ssh_username
    override.ssh.private_key_path   = google_local_ssh_key
    google.scopes                   = ['storage-ro','logging-write']
  end

  config.vm.box = "gce"
end

**Comment by Temikus** [comment]
@soudaburger I initially thought this is an issue with how Vagrant processes the Vagrant file, but I cannot reproduce this.

Following sample.yaml:
```
name: temikus
```
Following vagrantfile:
```
require 'pry'
require 'yaml'

settings = YAML.load_file 'sample.yml'
vagrant_google_ssh_username = settings['name']

Vagrant.configure("2") do |config|

  config.vm.box = "gce"

  config.vm.provider :google do |google, override|
      google.google_project_id = REDACTED
      google.google_client_email = REDACTED
      google.google_key_location = REDACTED

      puts "I got this when reading the block: #{vagrant_google_ssh_username}"

      override.ssh.username = vagrant_google_ssh_username
      override.ssh.private_key_path = "~/.ssh/id_rsa"

    google.zone = "europe-west1-d"

    google.zone_config "europe-west1-d" do |zone1d|
      zone1d.image = "debian-7-wheezy-v20150127"
      zone1d.zone = "europe-west1-d"
      zone1d.disk_type = "pd-ssd"
    end
  end
end
```
Vagrant successfully picks up the variable on all config reads:
```
λ vagrant up

I got this when reading the block: temikus
I got this when reading the block: temikus
I got this when reading the block: temikus
I got this when reading the block: temikus
I got this when reading the block: temikus
Bringing machine 'default' up with 'google' provider...
```
I can successfully `vagrant ssh` into the machine after.

I would suggest checking your Vagrantfile and load order very carefully and debug it a bit.
If you still can't find the issue, please, provide a reproducible scenario, i.e. vagrantfile + full corresponding yaml (change private data to REDACTED).

**Comment by soudaburger** [comment]
Yeah, so after looking at your code, and then running in debug mode, I found my problem.  PEBCAK!  I was CERTAIN that everything was set up correctly, but I was importing the wrong variable.  Thanks for the assist!
