### ISSUE TITLE
how long does it take for ssh to be available?

### ISSUE THREAD

**Issue by vinhdizzo** [mitchellh/vagrant-google#127]
Hi,

I just installed vagrant and vagrant-google on a CentOS machine.  After `vagrant up --provider=google`, there does not seem to be progress after:
```sh
==> default: Waiting for instance to become "ready"...
==> default: Machine is booted and ready for use!
==> default: Waiting for SSH to become available...
```
I'm not sure if this is due to me misconfiguring my ssh credentials or not.  I just followed the README.  Any thoughts?

After a few minutes I control-C to exit out:
```sh
^C==> default: Waiting for cleanup before exiting...
==> default: Machine is ready for SSH access!
==> default: Terminating the instance...

Vagrant exited after cleanup due to external interrupt.
```

**Comment by vinhdizzo** [comment]
I turned on debugging and found that there was a problem with the key: I pasted my username in front of the public key per [this](https://realguess.net/2015/09/07/setup-development-environment-with-vagrant-on-google-compute-engine/) post. I removed it and things work now.

**Comment by Temikus** [comment]
Glad to hear you got it working!
 I'll submit a FR to review the workflow a bit later and see if we can either fail fast or verify the key.
