### ISSUE TITLE
Investigate centos-7-v20160301 image tty issues

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#134]
```
stderr: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p '/vagrant'

Stdout from the command:



Stderr from the command:

sudo: sorry, you must have a tty to run sudo
```

**Comment by ericmand** [comment]
I got around this by using startup scripts:
google.metadata = {"startup-script" => "#!/bin/bash\necho 'Defaults:root !requiretty' > /etc/sudoers.d/gce && echo 'Defaults:#{SSH_USERNAME} !requiretty' >> /etc/sudoers.d/gce"}

**Comment by utdrmac** [comment]
Same issue. In your Vagrantfile add `override.ssh.pty = true` Simple solution.

**Comment by Temikus** [comment]
Fixed in later CentOS images.
