### ISSUE TITLE
README.md "Google Cloud Platform Setup" is outdated

### ISSUE THREAD

**Issue by DazWilkin** [mitchellh/vagrant-google#138]
Steps possibly 1 and 4 need revising to accommodate the new console structure:

console.developers.google.com is now the API Console
console.cloud.google.com is the Cloud Console

It may be better to stick with Cloud Console and refer developers directly to service URLs:

https://console.cloud.google.com/apis/library
https://console.cloud.google.com/apis/credentials

**Comment by Temikus** [comment]
@DazWilkin Thanks for pointing this out, submitted a fix. PTAL.

**Comment by DazWilkin** [comment]
LGTM, thanks!

Minor (!!) points:

It is possible to link directly to the "Google Compute Engine API":

https://console.cloud.google.com/apis/api/compute_component/

I think it's preferable to have developers create a new service account for Vagrant provider.

**Comment by Temikus** [comment]
@DazWilkin Done. PTAL.

**Comment by DazWilkin** [comment]
LGTM, thanks!
