### ISSUE TITLE
[FR] Support image families

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#144]
Support `image_family` parameter when this is implemented:
https://github.com/fog/fog-google/issues/131

**Comment by lonniev** [comment]
If !image && image_family
then image := `gcloud compute images list|grep $image_family|choose-latest`

or something like that.

**Comment by Temikus** [comment]
@lonniev There is progress towards it, I already implemented image_family in Fog, left to code it into Vagrant: https://github.com/fog/fog-google/pull/149

I'm a bit tight on time right now, but I'm always happy to help with design / review PR's!

**Comment by jim-raney-physiq** [comment]
This is an itch I've needed to scratch for a while.  I just submitted a PR: https://github.com/mitchellh/vagrant-google/pull/177

I'm not really a ruby programmer, let me know if there's anything I should do better or differently.

**Comment by tterranigma** [comment]
This is implemented now, right?

**Comment by Temikus** [comment]
@tterranigma This _is_ implemented, however, there turned out to be some corner-cases due to how `finalize!` logic works. The method gets called multiple times for each part of the config and then the config parameters get merged, where necessary. This introduced some issues in multi-zone and no-zone setups that I'm trying to work around.

So far it looks like I'll have to just overwrite whatever parameter the `image` has if `image_family` has been specified in effort to avoid brittle logic in `finalize!` method.

I'm a bit strapped for time so will be able to get to it and cutting a new gem in the next 2 weeks or so.

**Comment by Temikus** [comment]
The corner issues should be fixed as of 2.0: #181
