### ISSUE TITLE
vagrant up, vagrant status, vagrant destroy - hang

### ISSUE THREAD

**Issue by viktorbenei** [mitchellh/vagrant-google#150]
We saw this happen a couple of times, for some reason `vagrant up` or `vagrant status` or `vagrant destroy` just hangs and never finishes.

The weird thing is, this issue seems to be related to the `us-east1` region. We run the exact same config in two different regions, started with `us-central1-c` and `us-east1-c`, saw this error to happen on `us-east1-c` but not on `us-central`, so we moved to `us-east1-d` where the issue still happened, meanwhile `central` remained stable (no hanging issue at all).

We re-built the VM templates, updated vagrant to the latest version etc. but the issue remained, only on `us-east1`. Then we moved from `us-east1` to `us-west1-b`, and so far no hangs. The whole time `us-central` remained "hang free".

__For timeline__: we started to see this hanging a couple of weeks ago, I'd say about 3-4 weeks ago when we used `us-central1-c` and `us-east1-c`.

Only a couple of times per week (and we do well over 1000+ creates & destroys every day). Then we tried to update vagrant and rebuild the templates, start new instances from the new template (we never do updates on existing instances, we always create new templates and start new instances for any tool update). The issue remained the same. So, after about one week we moved to `us-east1-d`, tested it for another week, saw the hangs with about the same frequency. 

Then, the next week (this week actually) we moved to `us-west1-b`, and so far no hangs - hopefully it remains like this ;)

**Comment by Temikus** [comment]
Thanks for filing this! (Keep em' coming 👍 )

I will need at some info on what particular step do instances hang on. Do you have any STDOUT/STDERR records for instances hanging? I want to have an idea which step the action hangs on.

**Comment by viktorbenei** [comment]
I'll try to reproduce the issue, but that might take some time - as I mentioned this only happened a couple of times per week, but I'll do my best ;)

**Comment by viktorbenei** [comment]
Interesting, with the latest version of the plugin (0.2.5) we didn't see this issue to happen on `us-east` so far. It's been almost a week now, so the issue should have happened. Maybe the `fog` gem update fixed the issue?..

Anyway, we'll keep running the test this week, and let you know if we'd see it happen again.

**Comment by Temikus** [comment]
Great to hear! Thanks for the update.

There were quite a bit of fixes between those fog releases (esp. with the instance group handling) so you may not be that far off. Let me know if that happens again though.

**Comment by viktorbenei** [comment]
We checked everything and since 0.2.5 there was no hang issue, so I guess this can be marked as solved ;)

Thank you for your time and help!

**Comment by Temikus** [comment]
Awesome, glad to hear it's working! 👍
