### ISSUE TITLE
No shell provisioner output

### ISSUE THREAD

**Issue by utdrmac** [mitchellh/vagrant-google#153]
Not sure if this is a google-plugin issue or not as I'm only testing this one case. I'm creating instances in Google and using a simple shell/bash provisioning script. I do not see output from the script as things happen. I only see the entire output after ALL of the script has executed.

How can I get output to be displayed as it is executing?

**Comment by Temikus** [comment]
@utdrmac AFAIK it's WAI due to how vagrant processes actions, you should get the same with local Virtualbox.
