### ISSUE TITLE
rsync__args not respected

### ISSUE THREAD

**Issue by cledoux** [mitchellh/vagrant-google#158]
It appears that the options to the rsync command are currently [hard coded](https://github.com/mitchellh/vagrant-google/blob/master/lib/vagrant-google/action/sync_folders.rb#L81).

This is breaking my current Vagrantfile which relies on custom arguments to rsync defined via rsync__args.

My specific problem is that the I use links from a central folder into the shared directory and the `--archive` option causes these links to be copied as links rather than dereferencing before copying as I want. I normally override this behavior by providing my own options to rsync and excluding `--archive`.

I can work around this issue for now by reversing my link's direction (store actual file in share, place link in my central folder).

**Comment by Temikus** [comment]
Thanks for submitting this @cledoux !

Yeah, I was hoping we could upgrade to Vagrant's built-in rsync, but there's no NFS provider_capability and it doesn't seem to be going anywhere https://github.com/mitchellh/vagrant/issues/6781, so I'll probably have to do a hack or something.

If you have an idea on how to turn off NFS support on provider level - do tell me! I'm also always more than happy to review PR's.

**Comment by Temikus** [comment]
@cledoux This should be fixed, new release that uses built-in rsync is now available.
