### ISSUE TITLE
Path to ssh key is resolved relative to cwd, not Vagrantfile

### ISSUE THREAD

**Issue by luto** [mitchellh/vagrant-google#159]
All the paths given in a `Vagrantfile` are resolved relative to the file itself, for example the ansible provisioners `ansible.playbook = "site.yml"`. This plugin always resolves the location of the SSH key relative to the current working directory. This breaks as soon as the user tries to execute a `vagrant`-command in a subdirectory.

Instead the plugin should look for the SSH key files relative to the `Vagrantfile`.

If you agree that this should be changed, I'll be more than happy to prepare a PR for it.

**Comment by Temikus** [comment]
@luto Sorry for the late response.

Yeah, I do see your point, I think it makes sense to do it, esp. considering that current directory is quite a variable when it comes to Vagrant installed as a driver.

I'll need to bump the version to next major one though as it's, in theory, a breaking change.

**Comment by luto** [comment]
Alright. I will take a closer look at where this path is resolved and prepare a PR. Thanks!
