### ISSUE TITLE
Add support for internal_ip

### ISSUE THREAD

**Issue by zaterio** [mitchellh/vagrant-google#160]
When an instance is created,  it is possible to assign a Static IP :

gcloud compute instances create [INSTANCE_NAME] --private-network-ip [IP_ADDRESS]

https://cloud.google.com/compute/docs/configure-instance-ip-addresses

I have not found a way to do this using this provider.

This feature would be appreciated.

Regards

**Comment by Temikus** [comment]
@zaterio Thanks for the suggestion! Sorry it took a while to respond.

Good feature to add, I agree. I don't have time at the moment to code this in, but I'm more than happy to review a PR if you want to do this.

This should be basically a two-line change as soon as it's implemented in fog: https://github.com/fog/fog-google/issues/217

**Comment by aleks-mariusz** [comment]
@Temikus any chance you could review @andrewh1978's PR soon and merge if appropriate?

**Comment by Temikus** [comment]
@aleks-mariusz Just released `2.5.0` with the changes.
