### ISSUE TITLE
no config option for image-project

### ISSUE THREAD

**Issue by swills** [mitchellh/vagrant-google#161]
gcloud lets you get images from others projects via the --image-project flag. I'd like to do that for a vagrant box, but there's no option for it. Maybe this is missing in fog-google, not sure yet. As is, I can specify the image, but will have to copy it into my project to use it, otherwise I get an "Invalid image specified" error.

**Comment by Temikus** [comment]
@swills Fog does search inside own project for images, however, looking diagonally through the code it seems that one cannot specify another foreign project to search for images in: https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/models/images.rb#L89

Is the project you're having issues private or global (like `centos-cloud`)?
If it's global, it's basically a 1-line PR to add it here: https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/models/images.rb#L11

**Comment by seanmalloy** [comment]
@swills i created #186 to implement this feature. I tested in my environment and confirmed it is working.
