### ISSUE TITLE
Firewalls allow http/https support? 

### ISSUE THREAD

**Issue by KjetilM** [mitchellh/vagrant-google#162]
Been looking for the setting to use when allowing http traffic into boxes. 
The can_ip_forward i guess is tied to "IP forwarding on/off" not the fiewall settings?

**Comment by KjetilM** [comment]
I discovered that setting the tag 'http-server' actually sets the predefined firewall for http 

So setting tag 'http-server' activates the default firewall rule to allow http to active, and tag 'https-server' will do the same for https firewall rule.

**Comment by Temikus** [comment]
@KjetilM Correct, it is tied to "IP forwarding", which is propagated to kernel parameters.

`http-server` is a built-in tag, but one can specify others. You can associate firewall rules to a specific tag. See `sourceTags` and `targetTags` here: https://cloud.google.com/compute/docs/networking

**Comment by Temikus** [comment]
I'm closing this issue since this looks resolved.
However, if you still have any questions - no worries at all - just reopen and I'll help you right out!
