### ISSUE TITLE
Subnetwork support

### ISSUE THREAD

**Issue by Wyosotis** [mitchellh/vagrant-google#164]
I attempt to specify network for GCE instance. 

`google.network = "qwe-psr-vpn"`

And I get error while vagrant up 

```
There was an error talking to Google. The error message is shown
below:

Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network

```
I think I should also specify subnetwork name

`google.subnetwork = "qwe-psr-vpn-net"`

But there is no such available option. 

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Google Provider:
* The following settings shouldn't exist: subnetwork
```

Is there a possibility to add this support for vagrant-plugin? Thank you for answering.

**Comment by Temikus** [comment]
@Leila-Kuntar Sorry for a somewhat late response.

So, that does indeed look like a problem, I'll add it to my backlog of things to work through but I'm quite strapped for time at the moment. If you want to help with this I'd be more than happy to review a PR though.
