### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#171]
With support of subnetwork and stabilization, we need to get this plugin to stable.

However it looks like releasing a new version is not entirely trivial due to some dependency issues and the fact that bundler now disallows the hack that Vagrant uses to load up plugins in development.

I'll need some time to wrangle with it and do a prerelease.
I expect to address this sometime this/next week.

**Comment by tterranigma** [comment]
This is closed.
