### ISSUE TITLE
Add support for deploying Windows instances

### ISSUE THREAD

**Issue by nkakouros** [mitchellh/vagrant-google#173]
RIght now, if I set `config.vm.communicator = "winrm"`, I get a this warning on `vagrant up`:

```
==> windows-instance: Warning! The Google provider doesn't support any of the Vagrant                                                                                                                                                    
==> windows-instance: high-level network configurations (`config.vm.network`). They                                                                                                                                                      
==> windows-instance: will be silently ignored. 
```
This results in `vagrant up` getting stuck waiting for an ssh connection.

**Comment by Temikus** [comment]
@tterranigma I'm not familiar with WinRM enough to build this out quickly as it seems this needs specific capability to be built out, like in the Azure provider: https://github.com/Azure/vagrant-azure

I'm more than happy to review a pull request and/or help with building it out if you're willing to assist.

**Comment by tterranigma** [comment]
Hey @Temikus , I am sorry but I no longer use this project.  Thank you for you work all this time.

**Comment by dvanbrug** [comment]
@Temikus, would you still be willing to help with a pull request on this?  I've got something that seems to work but would appreciate having someone more familiar with the codebase taking a look.

**Comment by Temikus** [comment]
@dvanbrug Definitely. Although I may need a week+ to address it as my life is a bit hectic at the moment.

**Comment by dvanbrug** [comment]
@Temikus, Great!  No worries on the timeframe.  I'll submit a pull request as a starting point and we can go from there.
