### ISSUE TITLE
ffi dependency prevents installation with Vagrant 2.0.3

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#183]
@seanmalloy You've added a strict ffi dependency in https://github.com/mitchellh/vagrant-google/pull/180/commits/8e1f559e1be9c0885da90ad48df03027ee926e48 
Sorry for pinging but can you help me understand why it's needed (since vagrant already has it vendored) and why a strict version lock to `1.9.18` is required? I want to make sure I don't break you in some way by removing it.

I'm planning to get rid of it since this is breaking installation into standalone vagrant `2.0.3` on MacOSX:
```
λ vagrant plugin install vagrant-google --plugin-version 2.0.0.rc0
Installing the 'vagrant-google --version '2.0.0.rc0'' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies ffi (= 1.9.18) and ffi (= 1.9.23)
  Activated ffi-1.9.23
  which does not match conflicting dependency (= 1.9.18)

  Conflicting dependency chains:
    ffi (= 1.9.23), 1.9.23 activated

  versus:
    vagrant-google (= 2.0.0.rc0), 2.0.0.rc0 activated, depends on
    ffi (= 1.9.18)
```

**Comment by seanmalloy** [comment]
@Temikus when I run `bundle` on my machine to install the gems for development purposes versions of ffi greater than 1.9.18 would not compile. I'm running Fedora 27. I believe the Ruby version on Fedora 27 is Ruby 2.5. Version 1.9.18 of ffi compiles just fine, but anything newer than that does not compile. I did not dig into why it was not compiling.

I think you can go ahead and remove the hard coded ffi version to fix this issue. Sorry for breaking this.

**Comment by Temikus** [comment]
@seanmalloy Ack, thanks for the details.

FYI the vagrant's current built-in version of ruby is 2.4.3:
```
λ /opt/vagrant/embedded/bin/ruby --version
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin13]
```
I highly recommend installing `rbenv` and install a ruby version as close to that as possible.
