### ISSUE TITLE
reload isn't calling rsync

### ISSUE THREAD

**Issue by alechp** [mitchellh/vagrant-google#20]
After running vagrant reload:

"Vagrant attempted to call the action 'reload' on the provider
'Google (sparkmy)', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this
action, and should be reported."

**Comment by erjohnso** [comment]
I can look at fixing up the error message, but I don't think it makes sense to support `reload` (https://docs.vagrantup.com/v2/cli/reload.html) for a cloud provider. For instance, you wouldn't be able to change options such as location/zone or machine_type/size without first destroying the VM and then re-creating a new one.

I see that the AWS vagrant plugin does support reload, but they've really just turned that into a stop/start. So changes in the Vagrantfile would not get picked up.
