### ISSUE TITLE
Build fails due to incompatible versions of "childprocess"

### ISSUE THREAD

**Issue by dvanbrug** [mitchellh/vagrant-google#236]
Building fails with the following error.

> Bundler could not find compatible versions for gem "childprocess":
>   In Gemfile:
>     vagrant was resolved to 2.2.4, which depends on
>       childprocess (~> 0.6.0)
> 
>     vagrant-spec was resolved to 0.0.1, which depends on
>       childprocess (~> 3.0.0)

It looks like `vagrant-spec` recently updated to childprocess 3.0.0 (April 2, 2020, ab145fa).

I've worked around this locally by updating my Gemfile on line 30 to look like this:

```
gem 'vagrant-spec', git: "https://github.com/hashicorp/vagrant-spec.git", :ref => '161128'
```

The latest version of vagrant master branch has been updated to the same dependency but it does not look like they've released a tagged release with the update yet.

**Comment by Temikus** [comment]
Yeah, `vagrant-spec` has no gem or tagged releases so it's a bit of a tricky situation, but tests are generally easier with it than without it, as they cover use-cases I'm not usually thinking of (like chef provisioning).

I think it's fair to just leave it at the ref for now, it's only a dev dep anyway.
