### ISSUE TITLE
fog 1.2.5

### ISSUE THREAD

**Issue by LeviRosol** [mitchellh/vagrant-google#25]
on vagrant up we're seeing this:

```/Users/brad/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/google/core.rb:107:in `new_pk12_google_client': uninitialized constant Fog::VERSION (NameError)
    from /Users/brad/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/google/core.rb:85:in `initialize_google_client'
    from /Users/brad/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/google/compute.rb:1058:in `initialize'
    from /Users/brad/.vagrant.d/gems/gems/fog-core-1.25.0/lib/fog/core/service.rb:115:in `new'
    from /Users/brad/.vagrant.d/gems/gems/fog-core-1.25.0/lib/fog/core/service.rb:115:in `new'
    from /Users/brad/.vagrant.d/gems/gems/fog-core-1.25.0/lib/fog/compute.rb:60:in `new'
    from /Users/brad/.vagrant.d/gems/gems/vagrant-google-0.1.4/lib/vagrant-google/action/connect_google.rb:41:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_box_url.rb:9:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'```

Since fog 1.2.5 just came out 5 days ago, we're assuming that an older version of fog will provide a bandaid fix.

What other solutions might there be?

**Comment by iceydee** [comment]
@mitchellh what do you want to do with this? vagrant-google is currently broken in its current state.
