### ISSUE TITLE
Rsync does not seem to work

### ISSUE THREAD

**Issue by yellow1912** [mitchellh/vagrant-google#27]
On vagrant provision I see:

```
default: Rsyncing folder: c:/Programming/xampp/htdocs/demo/ => /var/www
```

However, the content is not actually synced and nothing is uploaded to google VM.

**Comment by erjohnso** [comment]
Hi @yellow1912 - sorry, just now saw your issue.  Can you share relevant parts of your Vagnrantfile?  For instance, this one seems to work fine for rsync:

```
Vagrant.configure("2") do |config|
  config.vm.box = "gce"
  config.vm.synced_folder "/Users/erjohnso/tmp/", "/host-data"
  config.vm.synced_folder "/Users/erjohnso/", "/vagrant", disabled: true

  config.vm.provider :google do |google, override|
    google.google_project_id = "my-project-name"
    google.google_client_email = "foo@developer.gserviceaccount.com"
    google.google_key_location = "~/PRIVATE_KEY.p12"

    override.ssh.username = "erjohnso"
    override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end
end
```

**Comment by erjohnso** [comment]
Hi @yellow1912 - is this still an issue for you, or were you able to make it work?

**Comment by erjohnso** [comment]
Hi @yellow1912 - I'm going to close this out hoping you got it working. Feel free to raise it again if you're still seeing problems.

**Comment by yellow1912** [comment]
Im very sorry for the late reply. I havent had time to check this back
recently. If I do see it again I will raise the issue again.

Best

On Sat, Feb 28, 2015 at 7:40 PM, Eric Johnson <notifications@github.com>
wrote:

> Hi @yellow1912 <https://github.com/yellow1912> - I'm going to close this
> out hoping you got it working. Feel free to raise it again if you're still
> seeing problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant-google/issues/27#issuecomment-76524472>
> .
>



-- 
RubikIntegration - helping entrepreneurs to realize their dreams
http://rubikintegration.com/

Subscribe to our feed to get the latest News/Tips and Tricks:
http://feeds.feedburner.com/rubikintegration

Follow me on twitter:
http://twitter.com/rubikint
