### ISSUE TITLE
vagrant reload not working 

### ISSUE THREAD

**Issue by anilgautam** [mitchellh/vagrant-google#33]
Vagrant attempted to call the action 'reload' on the provider
'Google (name)', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this
action, and should be reported.

**Comment by Temikus** [comment]
Not implemented, as is the halt action. Adding to ToDo, will work on this.

**Comment by Temikus** [comment]
Implemented in the associated PR.
@anilgautam, please, let me know if you have any issues.
