### ISSUE TITLE
Support for other disk types

### ISSUE THREAD

**Issue by iceydee** [mitchellh/vagrant-google#37]
Would be really nice if we could have support for setting disk type.

Most importantly, this one:
https://cloud.google.com/compute/docs/disks/local-ssd

**Comment by Temikus** [comment]
Working on this, already submitted pull request https://github.com/mitchellh/vagrant-google/pull/38

**Comment by Temikus** [comment]
#38 was merged so should be resolved. However @iceydee, please, let me know if something is not working out for you.

/cc @erjohnso - resolved by #38

**Comment by erjohnso** [comment]
Thanks @iceydee and @Temikus !!
