### ISSUE TITLE
Implement support for JSON service account keys

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#41]
Google introduced a new Service Account key format (JSON) and over time this will likely become the preferred format. We should begin by supporting this new format soon. 

It is already implemented in fog (see https://github.com/fog/fog/pull/3417), so we just need to extend the support to the vagrant-google provider.

We will also need to update the docs to reflect this and change all quick start scenarios and Vagrantfiles to have json keys by default.

**Comment by Temikus** [comment]
/CC @erjohnso 
Can be closed once #48 is merged.

**Comment by erjohnso** [comment]
I'll likely forget since I didn't just merge #48. I'll close this out though since I think the PR can be a stand-in for the issue.
