### ISSUE TITLE
Switch to vagrant's built-in rsync support

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#85]
See sister project:
https://github.com/mitchellh/vagrant-aws/commit/2ac53e22404e0addf5011f62b4c2da86f7e78b81

**Comment by Temikus** [comment]
Implemented.

**Comment by bryanwb** [comment]
vagrant-google appears to still use the custom `SyncFolders` instead of builtin `SyncedFolders`

**Comment by Temikus** [comment]
@zackangelo I think I found a workaround. Would you be willing to test a beta version of the gem?

**Comment by zackangelo** [comment]
@Temikus sure! just let me know what I have to do
